### ISSUE TITLE
フレームワークの名前について

### ISSUE THREAD

**Issue by takahiro-saeki** [takahiro-saeki/respect-the-ariana#5]
一応今は[ariana grand](https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%AA%E3%82%A2%E3%83%8A%E3%83%BB%E3%82%B0%E3%83%A9%E3%83%B3%E3%83%87)に合うようなイメージのCSSフレームワークというざっくりしたイメージ感で申し訳ないけど、なるべく早めにフレームワークの名前は決めたい。
こういうのが良いっていうのあったりします？

**Comment by milamnote** [comment]
うーん、今はぱっと思いつきません。

どういった形式のフレームワーク（ #6 ）を目指すのか？で変わりそう。。

**Comment by takahiro-saeki** [comment]
確かにですね、そこをもっと深めないとなんともという部分か。。。

**Comment by takahiro-saeki** [comment]
#9 
こちらで続きを話す
