### ISSUE TITLE
何系のフレームワークにするか？

### ISSUE THREAD

**Issue by milamnote** [takahiro-saeki/respect-the-ariana#6]
#何系のフレームワークにするか？

今メインとして,CSS界では
１．マテリアル・デザイン
２．レスポンシブ・デザイン
３．アダプティブ・デザイン
とあり、それ毎にCSSフレームワークが違ったりするので、
まず、何系のフレームワークを目指すのか？が大事かも

ちなみに、Bootstrapならレスポンシブ・デザイン
これから来るのは、アダプティブ・デザインと言われていたりするのですが、、
（ここ含めると、AMPとかも触れるべきなのかしらんとか考えてしまふ）
どうしましょ？

**Comment by takahiro-saeki** [comment]
ちょっとベンチマークしてみます！
benchmarkってフォルダの中に書くベンチマークするフレームワークのサンプル入れておきますので、お時間ある時に見てもらえればと思います(小平さんの為にもサーバーにあげるなり、github pagesにあげるなりした方が良いかな？localで各自見て頂けると助かりますが汗)

**Comment by takahiro-saeki** [comment]
#9
